trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    cd app/spring-petclinic
    chmod +x mvnw
    ./mvnw clean package
  displayName: Build Spring Boot application


- task: CopyFiles@2
  inputs:
    SourceFolder: 'app/spring-petclinic/target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'petclinic-jar'

# ======================
# DOWNLOAD ARTIFACT
# ======================
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'petclinic-jar'
    downloadPath: '$(System.ArtifactsDirectory)'


# ======================
# COPY TO CONTROLLER VM
# ======================
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'controller-ssh'
    sourceFolder: '$(System.ArtifactsDirectory)/petclinic-jar'
    contents: '**/*.jar'
    targetFolder: '/home/ansibleroot/petclinic'


# ======================
# RUN ANSIBLE FROM CONTROLLER
# ======================
- task: SSH@0
  inputs:
    sshEndpoint: 'controller-ssh'
    runOptions: 'inline'
    inline: |
      set -e

      echo "Deploying Spring PetClinic via Ansible..."

      cd /home/ansibleroot/ansible

      cp /home/ansibleroot/petclinic/*.jar spring-petclinic.jar

      ansible-playbook -i inventory.ini deploy.yml