trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    cd app/spring-petclinic
    chmod +x mvnw
    ./mvnw clean package
  displayName: Build Spring Boot application


- task: CopyFiles@2
  inputs:
    SourceFolder: 'app/spring-petclinic/target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'petclinic-jar'